First we import Torch to work with PyTorch!

In [1]:
import torch

This is how tensors would look like if we initialised them with Torch.

In [2]:
x = torch.ones(2,2)
print(x)

tensor([[1., 1.],
        [1., 1.]])


In [9]:
x = torch.ones(2, 2, dtype=torch.float16)
print(x.dtype)

torch.float16


In [10]:
print(x.size())

torch.Size([2, 2])


In [11]:
x = torch.tensor([2.5, 0.1])
print(x)

tensor([2.5000, 0.1000])


In [12]:
x = torch.rand(2, 2)
y = torch.rand(2, 2)
print(x)
print(y)

tensor([[0.7037, 0.0854],
        [0.4641, 0.0737]])
tensor([[0.3086, 0.9811],
        [0.5687, 0.7071]])


In [14]:
z = x + y
z = torch.add(x, y) # equivalent to the above
print(z)

tensor([[1.0123, 1.0665],
        [1.0328, 0.7808]])


Every function with a trailing underscore will do an in-place operation. Here, we did an in-place addition on y.

In [15]:
y.add_(x) # in-place addition

tensor([[1.0123, 1.0665],
        [1.0328, 0.7808]])

In [16]:
z = x - y
z = torch.sub(x, y) # equivalent to the above
print(z)

tensor([[-0.3086, -0.9811],
        [-0.5687, -0.7071]])


In [17]:
z = x * y
z = torch.mul(x, y) # equivalent to the above
print(z)

tensor([[0.7124, 0.0911],
        [0.4794, 0.0576]])


In [18]:
z = x / y
z = torch.div(x, y) # equivalent to the above
print(z)

tensor([[0.6951, 0.0801],
        [0.4494, 0.0944]])


In [19]:
x = torch.rand(5, 3)
print(x)

tensor([[0.0039, 0.9392, 0.7801],
        [0.9669, 0.1117, 0.0067],
        [0.6054, 0.0755, 0.6520],
        [0.5969, 0.4436, 0.0156],
        [0.9071, 0.1503, 0.4941]])


In [20]:
print(x[:, 0]) # all rows, first column

tensor([0.0039, 0.9669, 0.6054, 0.5969, 0.9071])


In [21]:
print(x[1, 1])

tensor(0.1117)


In [23]:
print(x[1, 1].item())

0.11174041032791138


In [24]:
x = torch.rand(4, 4)
print(x)

tensor([[0.2158, 0.4246, 0.9004, 0.6362],
        [0.4385, 0.2797, 0.9316, 0.7273],
        [0.0109, 0.0768, 0.9684, 0.0113],
        [0.4217, 0.7600, 0.6269, 0.8643]])


In [26]:
y = x.view(-1, 8) # resize x to 8 columns
print(y)

tensor([[0.2158, 0.4246, 0.9004, 0.6362, 0.4385, 0.2797, 0.9316, 0.7273],
        [0.0109, 0.0768, 0.9684, 0.0113, 0.4217, 0.7600, 0.6269, 0.8643]])


Lets import numpy now.

In [27]:
import numpy as np

In [28]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [29]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


If both the variables are on CPU and not the GPU, then changing one will also change the other, because they'd be pointing at the same memory location!

In [30]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [43]:
a = np.ones(5, dtype=int)
print(a)

[1 1 1 1 1]


In [44]:
b = torch.from_numpy(a)
print(b)

tensor([1, 1, 1, 1, 1], dtype=torch.int32)


In [45]:
a += 1
print(a)
print(b)

[2 2 2 2 2]
tensor([2, 2, 2, 2, 2], dtype=torch.int32)


The code below checks if a CUDA-enabled GPU is available. If it is, it performs the following steps:

1. Sets the device to CUDA.
2. Creates a tensor y on the CUDA device with the same shape as x.
3. Moves tensor x to the CUDA device.
4. Adds tensors x and y, storing the result in z.
5. Prints the result z.
6. Converts z to a CPU tensor with torch.double data type and prints it.

In [48]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device=device)
    x = x.to(device)
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))

tensor([[2., 2.],
        [2., 2.]], device='cuda:0', grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], dtype=torch.float64, grad_fn=<ToCopyBackward0>)


In [49]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
